version: '3'
services: 
    account-service:
        container_name: account-service
        build: 
            context: ./account-service
            dockerfile: Dockerfile
        ports: 
            - "8000:8000"
        environment: 
            PORT: 8000
            MESSAGE_BUS: amqp://rabbitmq
            DB_URL: ${DB_URL}
            JWT_SECRET: ${JWT_SECRET}
            BCRYPT_SALT: ${BCRYPT_SALT}
        links: 
            - rabbitmq

    notification-service:
        container_name: notification-service
        build: 
            context: ./notification-service
            dockerfile: Dockerfile
        ports: 
            - "8001:8001"
        environment: 
            PORT: 8001
            MESSAGE_BUS: amqp://rabbitmq
            MAIL_TRAP_PASS: ${MAIL_TRAP_PASS}
            MAIL_TRAP_USER: ${MAIL_TRAP_USER}
        links: 
            - rabbitmq
    
    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${DB_NAME}
        ports:
            - "5433:5433" 
        volumes:
            - ./postgres/data/:/var/lib/postgresql/data/
    
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "8888:8888"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        restart: unless-stopped

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.8.3
